# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('slug', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('mail_id', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=user.models.upload_imagesTo)),
                ('auth', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['firstname'],
            },
        ),
    ]
